services:
  # 1. Backend REST API Web Service
  - type: web
    name: nbfc-backend-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true

  # 2. Frontend React / Vite Web Service
  - type: web
    name: nbfc-frontend-service
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        sync: false
